@HostAddress = http://localhost:5145

GET {{HostAddress}}/customers/
Accept: application/json

###

POST {{HostAddress}}/invoices/
Content-Type: application/json
Accept: application/json

{
  "customerId": "fb9588d0-f4cd-4132-91a4-78d1abed8dca",
  "items": [
    {
      "description": "Camera",
      "quantity": 1,
      "unitPrice": 500
    }
  ]
}

###

GET {{HostAddress}}/invoices
Accept: application/json
